### ISSUE TITLE
riscv32 cross compiler seems to have issues with libgloss?

### ISSUE THREAD

**Issue by mithro** [nathanrossi/meta-hdl#1]
When trying to build `MACHINE=picosoc bitbake picosoc-hx8k` you need the `riscv32` cross compiler. However, there seems to be an issue where `libgloss` package.

```
WARNING: libgloss-3.0.0-r0 do_package: QA Issue: libgloss: Files/directories were installed but not shipped in any package:
  /usr/lib/lib
  /usr/lib/lib/libnosys.a
  /usr/lib/lib/nosys.specs
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
libgloss: 3 installed and not shipped files. [installed-vs-shipped]
```

It seems weird that the path has *two* lib values in it.

**Comment by nathanrossi** [comment]
This should now be fixed with master of oe-core and poky.

http://git.openembedded.org/openembedded-core/commit/?id=69ce8ba6cc610f310ae28d988d487918906e6ef9

However I also went ahead and switched the `picosoc` machine to use `tclibc-baremetal` (see 238e4b3bb021a7ef2a17cdebd53e52d04c8a671a) so that the toolchain is not built with a libc since it is not required (the picosoc firmware handles providing `_start` and linker script).
